# Generated by Django 2.1.5 on 2019-03-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOfKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('wider_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.BranchOfKnowledge')),
            ],
        ),
        migrations.CreateModel(
            name='CountOfHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count_of_themes', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=250, unique=True)),
                ('dean', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department', to_field='department_name')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_entry', models.SmallIntegerField()),
                ('first_deadline_date', models.DateField(blank=True, null=True)),
                ('last_deadline_date', models.DateField(blank=True, null=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Specialty', to_field='specialty_name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=35, unique=True)),
                ('office_365_email', models.EmailField(max_length=254)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('branch', models.ManyToManyField(to='teacher.BranchOfKnowledge')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department', to_field='department_name')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Faculty', to_field='faculty_name'),
        ),
        migrations.AddField(
            model_name='countofhour',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.StudentGroup'),
        ),
        migrations.AddField(
            model_name='countofhour',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', to_field='teacher_name'),
        ),
    ]
