# Generated by Django 2.1.5 on 2019-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='google_scholar',
        ),
        migrations.AlterField(
            model_name='topicoffer',
            name='fact_count_of_themes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicoffer',
            name='year_of_work',
            field=models.SmallIntegerField(default=2019),
        ),
    ]
