# Generated by Django 2.1.5 on 2019-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190502_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'бакалавр'), ('master', 'магістр')], default='bachelor', max_length=10),
        ),
    ]
