# Generated by Django 2.1.5 on 2019-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190412_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.BranchOfKnowledge'),
        ),
    ]
