# Generated by Django 2.1.7 on 2019-05-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_google_scholar'),
        ('teacher', '0004_studentgroup_degree'),
    ]

    operations = [
    ]
