# Generated by Django 2.1.5 on 2019-04-29 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('average_mark', models.FloatField(blank=True, null=True)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('send_email', models.BooleanField(default=True)),
            ],
        ),
    ]
