# Generated by Django 2.1.5 on 2019-03-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        ('teacher', '0002_auto_20190314_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('year_of_entry', models.SmallIntegerField()),
                ('first_deadline_date', models.DateField(blank=True, null=True)),
                ('last_deadline_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department', to_field='department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=35, unique=True)),
                ('office_365_email', models.EmailField(max_length=254)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('average_mark', models.FloatField(blank=True, null=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Specialty', to_field='specialty_name')),
            ],
        ),
    ]
