# Generated by Django 2.1.5 on 2019-04-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=35, unique=True)),
                ('office_365_email', models.EmailField(max_length=254, unique=True)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('average_mark', models.FloatField(blank=True, null=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.StudentGroup')),
            ],
        ),
    ]
