# Generated by Django 2.1.7 on 2019-05-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodist',
            fields=[
                ('methodist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('send_email', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department')),
            ],
        ),
    ]
