# Generated by Django 2.1.5 on 2019-04-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methodist', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodist',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department'),
        ),
    ]
