# Generated by Django 2.1.5 on 2019-03-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('work_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork', to_field='work_name')),
            ],
        ),
    ]
