# Generated by Django 2.1.5 on 2019-04-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='work_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork', to_field='work_name'),
        ),
    ]
