# Generated by Django 2.1.5 on 2019-05-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='work_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork'),
        ),
    ]
