# Generated by Django 2.1.5 on 2019-04-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='work_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork'),
        ),
    ]
