# Generated by Django 2.1.5 on 2019-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
