# Generated by Django 2.1.5 on 2019-04-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAIT', 'очікується підтвердження'), ('CONFIRMED', 'підтверджкно викладачем'), ('REJECTED', 'відхилено викладачем'), ('BLOCKED', 'затверджено на іншу тему')], max_length=10)),
                ('date_of_record', models.DateTimeField(auto_now_add=True)),
                ('date_of_confirmation', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='WriteWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=500, unique=True)),
                ('english_work_name', models.CharField(max_length=500, unique=True)),
                ('year_of_work', models.SmallIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('branch', models.ManyToManyField(to='teacher.BranchOfKnowledge')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork')),
                ('student', models.ManyToManyField(through='theme.Record', to='student.Student')),
                ('teacher_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TopicOffer')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork', to_field='work_name'),
        ),
    ]
