# Generated by Django 2.1.5 on 2019-04-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.WriteWork'),
        ),
    ]
