# Generated by Django 2.1.5 on 2019-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writework',
            name='english_work_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='writework',
            name='student',
            field=models.ManyToManyField(blank=True, through='theme.Record', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='writework',
            name='work_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
