# Generated by Django 2.1.5 on 2019-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20190501_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('WAIT', 'очікується підтвердження'), ('CONFIRMED', 'підтверджкно викладачем'), ('REJECTED', 'відхилено викладачем'), ('BLOCKED', 'затверджено на іншу тему')], default='WAIT', max_length=10),
        ),
    ]
