# Generated by Django 2.1.5 on 2019-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20190502_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writework',
            name='work_name',
            field=models.CharField(max_length=250),
        ),
    ]
